### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by yuchen814** [Vance0124/Token-level-Direct-Preference-Optimization#2]
What a great work! 
But I encountered this bug while running the code, and I solved it by modifying the TemporarySeededRandom in utils. Is this normal?

Traceback (most recent call last):
  File "/home/tianyuchen/codehalu/Token-level-Direct-Preference-Optimization/train.py", line 115, in main
    mp.spawn(worker_main, nprocs=world_size, args=(world_size, config, policy, reference_model), join=True)
  File "/home/tianyuchen/anaconda3/envs/tpo/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 281, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tianyuchen/anaconda3/envs/tpo/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 237, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/home/tianyuchen/anaconda3/envs/tpo/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 188, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/tianyuchen/anaconda3/envs/tpo/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/home/tianyuchen/codehalu/Token-level-Direct-Preference-Optimization/train.py", line 48, in worker_main
    trainer.train()
  File "/home/tianyuchen/codehalu/Token-level-Direct-Preference-Optimization/trainers.py", line 378, in train
    for batch in self.train_iterator:
  File "/home/tianyuchen/codehalu/Token-level-Direct-Preference-Optimization/preference_datasets.py", line 429, in get_batch_iterator
    with TemporarilySeededRandom(next(permutation_seeds)):
  File "/home/tianyuchen/codehalu/Token-level-Direct-Preference-Optimization/utils.py", line 169, in __enter__
    random.seed(self.seed)
  File "/home/tianyuchen/anaconda3/envs/tpo/lib/python3.12/random.py", line 167, in seed
    raise TypeError('The only supported seed types are: None,\n'
TypeError: The only supported seed types are: None,
int, float, str, bytes, and bytearray.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Vance0124** [comment]
Sorry, we did not encounter this issue in our experiments.

The error message indicates that the seed value passed to `random.seed()` in the `TemporarilySeededRandom` class is of an unsupported type. To investigate further, we suggest checking the state and attributes of `self.seed` to identify where an unsupported type might be introduced. This can help pinpoint the root cause.

Additionally, you can set the environment variable `HYDRA_FULL_ERROR=1` to obtain more detailed error information. Add the following line to your code to set this environment variable:

```python
os.environ['HYDRA_FULL_ERROR'] = '1'
```

This will provide more comprehensive error tracking for debugging purposes.

Thank you for your kind words. If you have any more questions, feel free to reach out.

**Comment by yuchen814** [comment]
Thanks for your prompt reply!
I found the type of "permutation_seeds" is <class 'iterator'>, and type of "next(permutation_seeds) " is <class 'numpy.int64'>. It seems that random. seed() cannot work on numpy types.
I changed the class named 'TemporarilySeededRandom' in utils.py like this:

class TemporarilySeededRandom:
    def __init__(self, seed):
        """Temporarily set the random seed, and then restore it when exiting the context."""
        self.seed = seed
        self.stored_state = None
        self.stored_np_state = None

    def __enter__(self):
        # Check if the seed is an iterator and get the next value if it is
        if hasattr(self.seed, '__iter__'):
            self.seed = next(self.seed)

        # Convert numpy.int64 to Python int if necessary
        if isinstance(self.seed, np.integer):
            self.seed = int(self.seed)

        # Ensure the seed is of a supported type
        if not isinstance(self.seed, (int, float, str, bytes, bytearray)):
            raise TypeError(f"Unsupported seed type: {type(self.seed)}")

        # Store the current random state
        self.stored_state = random.getstate()
        self.stored_np_state = np.random.get_state()

        # Set the random seed
        random.seed(self.seed)
        np.random.seed(self.seed)

    def __exit__(self, exc_type, exc_value, traceback):
        # Restore the random state
        random.setstate(self.stored_state)
        np.random.set_state(self.stored_np_state)

Do you think it's OK?
 
.

**Comment by Vance0124** [comment]
We tested the issue you mentioned on multiple machines and found that it does indeed occur on some of them. This is likely due to updates and changes in the Python version. We have modified the code accordingly：
~~~
class TemporarilySeededRandom:
    def __init__(self, seed):
        """Temporarily set the random seed, and then restore it when exiting the context."""
        self.seed = int(seed)    # convert to int type
        self.stored_state = None
        self.stored_np_state = None

    def __enter__(self):
        # Store the current random state
        self.stored_state = random.getstate()
        self.stored_np_state = np.random.get_state()

        # Set the random seed
        random.seed(self.seed)
        np.random.seed(self.seed)

    def __exit__(self, exc_type, exc_value, traceback):
        # Restore the random state
        random.setstate(self.stored_state)
        np.random.set_state(self.stored_np_state)
~~~
Hope you can try again! 

Thank you very much for your valuable feedback!
